apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: my-app-namespace
  labels:
    app: my-app
    tier: backend
spec:
  type: ClusterIP # Internal service
  selector:
    app: my-app
    tier: backend
  ports:
  - protocol: TCP
    port: 5000 # Service port
    targetPort: 5000 # Container port
